language: node_js

install:
  - npm i -g npm@6
  - npm ci

script:
  - npm run lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: a2148a7096d6bd06105adf5621ba2f8563ff92fe
  local-dir: public
  on:
    branch: master

cache:
  directories:
    - "node_modules"