language: node_js

script:
  - npm run lint
  - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master