language: node_js

install:
  - npm i -g npm@6
  - npm ci

script:
  - npm run lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 9df09e930ad09bf59fa683dc1f1006d81a6bf655
  local-dir: public
  on:
    branch: master

cache:
  directories:
    - "node_modules"