language: node_js

install:
  - npm i -g npm@6
  - npm ci

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master